# Generated by Django 3.1.5 on 2021-01-29 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_posts_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='instructors',
            name='courses_taught',
        ),
        migrations.RemoveField(
            model_name='instructors',
            name='department',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='user',
        ),
        migrations.DeleteModel(
            name='Courses',
        ),
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.DeleteModel(
            name='Instructors',
        ),
        migrations.DeleteModel(
            name='Reviews',
        ),
    ]
