# Generated by Django 3.1.5 on 2021-01-30 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20210130_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='topic',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='pages.topic'),
        ),
    ]
