# Generated by Django 3.1.5 on 2021-02-02 10:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0011_sub_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_comments',
            name='comment',
        ),
        migrations.AddField(
            model_name='sub_comments',
            name='comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pages.comments'),
        ),
    ]
