# Generated by Django 3.1.5 on 2021-02-02 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0014_auto_20210202_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='vote_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
