# Generated by Django 3.1.5 on 2021-01-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_posts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='comment_cout',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posts',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
    ]
