# Generated by Django 3.1.5 on 2021-01-29 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_courses_departments_instructors_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
