# Generated by Django 3.1.5 on 2021-01-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_auto_20210130_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='anonymous',
            field=models.BooleanField(default=False),
        ),
    ]
